# Generated by Django 3.1.4 on 2021-01-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201231_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(max_length=200)),
                ('rent_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts from Apartments listed for Rent',
            },
        ),
        migrations.CreateModel(
            name='SaleContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=200)),
                ('sale_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts from Apartments listed for Sale',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
