# Generated by Django 3.1.4 on 2021-01-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210101_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Property Management',
            },
        ),
        migrations.AlterField(
            model_name='rentcontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='salecontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
