# Generated by Django 3.1.1 on 2020-12-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sold',
            new_name='occupied',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('sell', 'For Sale'), ('rent', ' For Rent')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
