# Generated by Django 3.1.1 on 2020-12-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201229_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='occupied',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
    ]
