# Generated by Django 3.1.4 on 2021-01-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name_plural': 'Apartments for Rent'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Apartments for Sale'},
        ),
    ]
